---
- include_tasks: "{{ ansible_distribution }}_prepare.yml"

- name: Copy wpa_supplicant configs
  ansible.builtin.copy:
    src: "{{ wpa_supplicant_config_file }}"
    dest: "/etc/wpa_supplicant/wpa_supplicant-{{ wireless_interface }}.conf"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: systemctl enable --now wpa_supplicant@{{ wireless_interface }}.service
  ansible.builtin.systemd: name=wpa_supplicant@{{ wireless_interface }}.service state=started enabled=true
  become: true
