---
- name: Delete default network configuration on Archlinux
  ansible.builtin.file:
    path: /etc/systemd/network/20-ethernet.network
    state: absent
  become: true
  when: ansible_distribution == "Archlinux"

- name: apt install systemd-resolved
  ansible.builtin.apt: name=systemd-resolved state=present
  become: true
  when: ansible_distribution == "Debian"

- name: Check /etc/network/interfaces on Debian
  ansible.builtin.stat:
    path: /etc/network/interfaces
  register: network_interfaces
  become: true
  when: ansible_distribution == "Debian"

- name: Remove /etc/network/interfaces on Debian
  ansible.builtin.command: mv /etc/network/interfaces /etc/network/interfaces.save
  become: true
  when: ansible_distribution == "Debian" and network_interfaces.stat.exists

- name: Copy systemd-networkd configs
  ansible.builtin.copy:
    src: "{{ networkd_configs_dir }}"
    dest: /etc/systemd/network/
    owner: root
    group: root
    mode: '0644'
  become: true

- name: systemctl enable systemd-networkd
  ansible.builtin.systemd: name=systemd-networkd enabled=true
  become: true

- name: systemctl enable systemd-resolved
  ansible.builtin.systemd: name=systemd-resolved enabled=true
  become: true
  when: ansible_distribution == "Debian"
    
