---
- include_tasks: "{{ ansible_distribution }}-prepare.yml"

- name: "Create {{ static_nic }}.network"
  ansible.builtin.template:
    src: en0.network.j2
    dest: /etc/systemd/network/{{ static_nic }}.network
    owner: root
    group: systemd-network
    mode: '0640'
  become: true
  when: networkd_configs_dir is not defined

- name: Copy systemd-networkd configs
  ansible.builtin.copy:
    src: "{{ networkd_configs_dir }}"
    dest: /etc/systemd/network/
    owner: root
    group: systemd-network
    mode: '0640'
  become: true
  when: networkd_configs_dir is defined

- name: systemctl enable systemd-networkd
  ansible.builtin.systemd: name=systemd-networkd enabled=true
  become: true

- name: systemctl enable systemd-resolved
  ansible.builtin.systemd: name=systemd-resolved enabled=true
  become: true

