---
- name: pacman -S cockpit cockpit-machines
  community.general.pacman:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-podman
    state: present
  become: true

- name: Modify cockpit.socket
  ansible.builtin.file:
    path: /etc/systemd/system/cockpit.socket.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
  when: cockpit_listen_address is defined

- name: Cockpit listening address
  ansible.builtin.copy:
    content: |
      [Socket]
      ListenStream=
      ListenStream={{ cockpit_listen_address }}:9090
      FreeBind=yes
    dest: /etc/systemd/system/cockpit.socket.d/listen.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  when: cockpit_listen_address is defined

- name: systemctl daemon-reload
  ansible.builtin.systemd_service: daemon_reload=true
  become: true

- name: systemctl enable --now cockpit.socket
  ansible.builtin.systemd_service: name=cockpit.socket enabled=true state=started
  become: true

- name: Set firewall rules for Cockpit
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" source address="{{ item }}" service name="cockpit" accept
    #zone: "{{ firewalld_default_zone }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ cockpit_accept_source_ipv4 }}"
  become: true
  when: cockpit_accept_source_ipv4 is defined
