---
- block:

  - name: Create br.netdev
    ansible.builtin.template:
      src: br.netdev.j2
      dest: /etc/systemd/network/{{ item.bridge_name }}.netdev
      owner: root
      group: root
      mode: '0644'

  - name: Create testing br.network
    ansible.builtin.template:
      src: br.network.j2
      dest: /etc/systemd/network/{{ item.bridge_name }}.network
      owner: root
      group: root
      mode: '0644'

  - name: Create tap.netdev
    ansible.builtin.template:
      src: tap.netdev.j2
      dest: /etc/systemd/network/{{ item.tap_name }}.netdev
      owner: root
      group: root
      mode: '0644'

  - name: Create tap.network
    ansible.builtin.template:
      src: tap.network.j2
      dest: /etc/systemd/network/{{ item.tap_name }}.network
      owner: root
      group: root
      mode: '0644'

  loop: "{{ testing_bridge_networks. }}"
  become: yes
