---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: ansible_become_password
      private: yes

  vars_files:
    - host_vars/gui_example.yml

  pre_tasks:
    #- name: Enable multilib repo
    #  blockinfile:
    #    path: /etc/pacman.conf
    #    insertafter: '^#\s*[multilib]'
    #    block: |
    #      [multilib]
    #      Include = /etc/pacman.d/mirrorlist
    #  become: yes

    - import_tasks: tasks/update.yml

  roles:
    - archlinux_common
    - gui
    - podman


