---
- hosts: headless_example

  vars_files:
    - host_vars/headless_example.yml

  pre_tasks:
    - import_tasks: tasks/update.yml

  roles:
    - archlinux_common
    - openssh
    - networkd_static
    - nas
    - msmtp
    - auto-update
    - ups
    - podman

