---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: ansible_become_password
      private: yes

  vars_files:
    - vars/test.yml

  pre_tasks:
    #- name: Enable multilib repo
    #  blockinfile:
    #    path: /etc/pacman.conf
    #    insertafter: '^#\s*[multilib]'
    #    block: |
    #      [multilib]
    #      Include = /etc/pacman.d/mirrorlist
    #  become: yes

    - import_tasks: tasks/update.yml


  roles:
    - common
    #- openssh
    - gui
    - libvirt
    - pip

  tasks:
    #- name: Enable DRM kernel mode setting for nvidia driver
    #  lineinfile:
    #    path: /etc/kernel/cmdline
    #    regexp: '^(.* rw)'
    #    line: \g<1> nvidia-drm.modeset=1
    #    backrefs: yes
    #  register: nvidia_KMS
    #  become: yes
    #- name: regenerate initramfs if kernel parameter changed
    #  command: pacman --noconfirm -S systemd
    #  become: yes
    #  when: nvidia_KMS is changed
       

  post_tasks:
    - import_tasks: tasks/ufw.yml
