---
- block:

  - name: Delete default network configuration
    ansible.builtin.file:
      path: /etc/systemd/network/20-ethernet.network
      state: absent

  - name: Configure network
    ansible.builtin.template:
      src: "{{ item.src }}"
      dest: /etc/systemd/network/{{ item.dest }}
      owner: root
      group: root
      mode: '0644'
    loop:
      - { src: en0.network.j2, dest: "{{ nic_name }}.network" }
      - { src: en0.vlan1.netdev.j2, dest: "{{ nic_name }}.{{ vlan1.id }}.netdev" }
      - { src: en0.vlan1.network.j2, dest: "{{ nic_name }}.{{ vlan1.id }}.network" }
      - { src: br_vlan0.netdev.j2, dest: "br{{ vlan0.id }}.netdev" }
      - { src: br_vlan0.network.j2, dest: "br{{ vlan0.id }}.network" }
      - { src: br_vlan1.netdev.j2, dest: "br{{ vlan1.id }}.netdev" }
      - { src: br_vlan1.network.j2, dest: "br{{ vlan1.id }}.network" }

  become: yes
