---
- name: pacman -S python-pip python-setuptools
  community.general.pacman:
    name:
      - python-pip
      - python-setuptools
    state: present
  become: yes

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_pkgs }}"
    extra_args: --user

