---
gpu_drivers:
  - mesa

shell_pkgs:
  - fish
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - grml-zsh-config

default_shell: /usr/bin/fish

wm_pkgs:
  - sway
  - swaylock
  - swayidle
  - dmenu
  - waybar
  - xdg-utils
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
  - python-i3ipc

audio_pkgs:
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - pipewire-jack
  - pavucontrol

fonts_pkgs:
  - ttf-dejavu
  - ttf-font-awesome

other_pkgs:
  - kitty
  - htop
  - neofetch
  - usbutils
  - rsync

flatpak_pkgs:
  - com.github.tchx84.Flatseal
