---
- name: pacman -S libvirt-python
  community.general.pacman:
    name: libvirt-python
    state: present

- name: Copy libvirt_start@.service libvirt_vm.py
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { src: libvirt_start@.service, dest: /etc/systemd/system/libvirt_start@.service, mode: '0644' }
    - { src: libvirt_vm.py, dest: /usr/local/bin/libvirt_vm.py, mode: '0744' }

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: systemctl enable libvirt_start@vm.service
  ansible.builtin.systemd:
    name: libvirt_start@{{ item }}.service
    enabled: yes
  loop: "{{ auto_start_vm_list }}"
