---
- name: autobrr container config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.autobrr_config_dir }}"
    state: directory
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true

- name: autobrr.service
  ansible.builtin.template:
    src: autobrr.service.j2
    dest: "/home/{{ podman_user.name }}/.config/systemd/user/autobrr.service"
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now autobrr.service
  ansible.builtin.systemd: name=autobrr.service enabled=true state=started scope=user
  become: true
  become_user: "{{ podman_user.name }}"
