---
- name: IP forwarding for routed trafic
  ansible.builtin.lineinfile:
    path: /etc/ufw/sysctl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: absent
  loop:
    - { regexp: '^net/ipv4/ip_forward', line: net/ipv4/ip_forward=1, insertafter: '^#net/ipv4/ip_forward' }
    - { regexp: '^net/ipv6/conf/default/forwarding', line: net/ipv6/conf/default/forwarding=1, insertafter: '^#net/ipv6/conf/default/forwarding' }
    - { regexp: '^net/ipv6/conf/all/forwarding', line: net/ipv6/conf/all/forwarding=1, insertafter: '^#net/ipv6/conf/all/forwarding' }

- name: UFW allow outgoing rules
  community.general.ufw:
    route: yes
    rule: allow
    interface_out: "{{ static_nic }}"
    comment: "Allow outgoing routed traffic"

