---
- block:
  - name: gluetun.service
    ansible.builtin.template:
      src: gluetun.service.j2
      dest: "/home/{{ podman_user }}/.config/systemd/user/gluetun.service"
      owner: "{{ podman_user }}"
      group: "{{ podman_user }}"
      mode: '0600'

  - name: systemctl --user enable gluetun.service
    ansible.builtin.systemd:
      name: gluetun
      enabled: yes
      scope: user

  #- name: Set ufw incoming rules for Jellyfin web interface
  #  community.general.ufw:
  #    route: yes
  #    rule: allow
  #    interface_in: "{{ static_nic }}"
  #    from_ip: "{{ item }}"
  #    to_ip: any
  #    proto: tcp
  #    port: 8096
  #    comment: "Allow access Jellyfin web interface (http) from {{ jellyfin_allow_from }}"
  #  loop: "{{ jellyfin_allow_from }}"

  become: yes
  become_user: "{{ podman_user }}"
