---
- block:
  - name: gluetun.service
    ansible.builtin.template:
      src: gluetun.service.j2
      dest: "/home/{{ podman_user.name }}/.config/systemd/user/gluetun.service"
      owner: "{{ podman_user.name }}"
      group: "{{ podman_user.name }}"
      mode: '0600'

  - name: systemctl --user enable gluetun.service
    ansible.builtin.systemd:
      name: gluetun
      enabled: yes
      scope: user

  become: yes
  become_user: "{{ podman_user.name }}"
