---
- name: homeassistant container config and data direcoty
  ansible.builtin.file:
    path: "{{ podman_user.homeassistant_config_dir }}"
    state: directory
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true

- name: homeassistant.service
  ansible.builtin.template:
    src: homeassistant.service.j2
    dest: "/home/{{ podman_user.name }}/.config/systemd/user/homeassistant.service"
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now homeassistant.service
  ansible.builtin.systemd: name=homeassistant enabled=true state=started scope=user
  become: true
  become_user: "{{ podman_user.name }}"
