---
- name: container config direcoty
  ansible.builtin.file:
    path: /opt/container-configs/jellyfin
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: jellyfin.service
  ansible.builtin.template:
    src: jellyfin.service.j2
    dest: /etc/systemd/system/jellyfin.service
    owner: root
    group: root
    mode: '0644'

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: systemctl enable jellyfin.service
  ansible.builtin.systemd:
    name: jellyfin
    enabled: yes

- name: Set ufw incoming rules for Jellyfin web interface
  community.general.ufw:
    route: yes
    rule: allow
    interface_in: "{{ static_nic }}"
    from_ip: "{{ jellyfin_allow_web_from }}"
    to_ip: any
    proto: tcp
    port: 8096
    comment: "Allow access Jellyfin web interface (http) from {{ jellyfin_allow_web_from }}"
  loop: "{{ jellyfin_allow_web_from }}"

