---
- block:
  - name: container config direcoty
    ansible.builtin.file:
      path: "{{ container_configs_dir }}/jellyfin"
      state: directory
      owner: "{{ podman_user }}"
      group: "{{ podman_user }}"
      mode: '0700'

  - name: jellyfin.service
    ansible.builtin.template:
      src: jellyfin.service.j2
      dest: "/home/{{ podman_user }}/.config/systemd/user/jellyfin.service"
      owner: "{{ podman_user }}"
      group: "{{ podman_user }}"
      mode: '0600'

  - name: systemctl --user daemon-reload
    ansible.builtin.systemd:
      daemon_reload: yes
      scope: user

  - name: systemctl --user enable jellyfin.service
    ansible.builtin.systemd:
      name: jellyfin
      enabled: yes
      scope: user

  become: yes
  become_user: "{{ podman_user }}"


- name: Set firewall rules for Jellyfin web interface
  ansible.posix.firewalld:
    rich_rule: "{{ item }}"
    zone: "{{ firewalld_default_zone }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ jellyfin_firewall }}"
  become: yes
