---
- block:
  - name: pacman -S podman
    community.general.pacman:
      name: podman
      state: present

  - name: container configs directory permision
    ansible.builtin.file:
      path: "{{ container_configs_dir.path }}"
      state: directory
      owner: "{{ container_configs_dir.owner }}"
      group: "{{ container_configs_dir.group }}"
      mode: "{{ container_configs_dir.mode }}"

  - import_tasks: common_ufw.yml

  - name: create podman-image-prune.service/timer and podman-bridges.service
    ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: '0644'
    loop:
      - podman-image-prune.service
      - podman-image-prune.timer
      - podman-bridges.service

  - name: systemctl daemon-reload
    ansible.builtin.systemd:
      daemon_reload: yes
  
  - name: systemctl enable podman-image-prune.timer and podman-bridges.service
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: yes
    loop:
      - podman-image-prune.timer
      - podman-bridges.service

  - include_tasks: "{{ container_name }}.yml"
    loop: "{{ containers }}"
    loop_control:
      loop_var: container_name

  become: yes
