---
- name: nextcloud container config and data direcoty
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ podman_user.name}}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true
  loop:
    - "{{ podman_user.nextcloud_config_dir }}"
    - "{{ podman_user.nextcloud_data_dir }}"
    - "{{ podman_user.postgres_config_dir }}"


- name: nextcloud-pod.service nextcloud.service postgres.service nextcloud-cron.service nextcloud-cron.timer
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/home/{{ podman_user.name }}/.config/systemd/user/{{ item }}"
    owner: "{{ podman_user.name}}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"
  loop:
    - nextcloud-pod.service
    - nextcloud.service
    - postgres.service
    - nextcloud-cron.service
    - nextcloud-cron.timer

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now nextcloud-pod.service nextcloud.service postgres.service nextcloud-cron.timer
  ansible.builtin.systemd: name={{ item }} state=started enabled=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"
  loop:
    - nextcloud-pod.service
    - nextcloud.service
    - postgres.service
    - nextcloud-cron.timer

# 4108/tcp  nextcloud port
- name: add nextcloud firewalld service file nextcloud.xml
  ansible.builtin.copy:
    content: |
      <?xml version="1.0" encoding="utf-8"?>
      <service>
        <short>Nextcloud</short>
        <description>Nextcloud</description>
        <port protocol="tcp" port="4108"/>
      </service>
    dest: /etc/firewalld/services/nextcloud.xml
    owner: root
    group: root
    mode: '0644'
  become: true
  register: nextcloud_firewalld_file

- name: Reload firewalld when nextcloud.xml changed
  ansible.builtin.command: firewall-cmd --reload
  become: true
  when: nextcloud_firewalld_file.changed

- name: Set firewall rules for nextcloud listening port (TCP)
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" source address="{{ reverse_proxy_ipv4 }}" service name="nextcloud" accept
    #zone: "{{ firewalld_default_zone }}"
    permanent: true
    immediate: true
    state: enabled
  become: true
  when: reverse_proxy_ipv4 is defined
