---
- name: pacman -S podman aardvark-dns
  community.general.pacman:
    name:
      - podman
      - aardvark-dns
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: apt install podman
  ansible.builtin.apt: name=podman state=present
  become: true
  when: ansible_distribution == "Debian"

- name: dnf install podman
  ansible.builtin.dnf: name=podman state=present
  become: true
  when: ansible_distribution == "Fedora"

# install acl package for ansible to become other unprivileged user
- name: apt install acl
  ansible.builtin.apt: name=acl state=present
  become: true
  when: ansible_distribution == "Debian"

- name: dnf install acl
  ansible.builtin.dnf: name=acl state=present
  become: true
  when: ansible_distribution == "Fedora"

- name: dnf install policycoreutils-python-utils
  ansible.builtin.dnf: name=policycoreutils-python-utils state=present
  become: true
  when: ansible_distribution == "Fedora"

#- name: Get file system type of /
#  ansible.builtin.command: stat --file-system --format=%T /
#  become: true
#  register: root_fstype
#  changed_when: false
#  check_mode: false
#
#- name: Get file system type of ~/
#  ansible.builtin.command: "stat --file-system --format=%T {{ ansible_user_dir }}"
#  become: true
#  register: home_fstype
#  changed_when: false
#  check_mode: false
#
#- name: Set container storage driver
#  ansible.builtin.lineinfile:
#    path: /etc/containers/storage.conf
#    regexp: '^driver\s*='
#    line: 'driver = "btrfs"'
#  become: true
#  when:
#    - root_fstype.stdout == 'btrfs'
#    - home_fstype.stdout == 'btrfs'

