---
- name: pacman -S podman fuse-overlayfs
  community.general.pacman:
    name:
      - podman
      - fuse-overlayfs
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: apt install podman crun
  ansible.builtin.apt:
    name:
      - podman
      - crun
    state: present
  become: true
  when: ansible_distribution == "Debian"

- name: dnf install podman
  ansible.builtin.dnf: name=podman state=present
  become: true
  when: ansible_distribution == "Fedora"

# install acl package for ansible to become other unprivileged user
- name: dnf install acl
  ansible.builtin.dnf: name=acl state=present
  become: true
  when: ansible_distribution == "Fedora"

- name: dnf install policycoreutils-python-utils
  ansible.builtin.dnf: name=policycoreutils-python-utils state=present
  become: true
  when: ansible_distribution == "Fedora"

