---
- name: pacman -S podman aardvark-dns
  community.general.pacman:
    name:
      - podman
      - aardvark-dns
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: apt install podman
  ansible.builtin.apt: name=podman state=present
  become: true
  when: ansible_distribution == "Debian"

- name: dnf install podman
  ansible.builtin.dnf: name=podman state=present
  become: true
  when: ansible_distribution == "Fedora"

# install acl package for ansible to become other unprivileged user
- name: dnf install acl
  ansible.builtin.dnf: name=acl state=present
  become: true
  when: ansible_distribution == "Fedora"

- name: dnf install policycoreutils-python-utils
  ansible.builtin.dnf: name=policycoreutils-python-utils state=present
  become: true
  when: ansible_distribution == "Fedora"

# Asahi Linux use ext4 for / therefore use default overlay fs
- name: Set container storage driver
  ansible.builtin.lineinfile:
    path: /etc/containers/storage.conf
    regexp: '^driver\s*='
    line: 'driver = "btrfs"'
  become: true
  when: homed or ansible_architecture == 'x86_64'

