---
- name: pacman -S podman fuse-overlayfs
  community.general.pacman:
    name:
      - podman
      - fuse-overlayfs
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: dnf install podman
  ansible.builtin.dnf: name=podman state=present
  become: true
  when: ansible_distribution == "Fedora"
