---
- name: qbittorrent container config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.qbittorrent_config_dir }}"
    state: directory
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true

- name: qbittorrent.container
  ansible.builtin.template:
    src: qbittorrent.container.j2
    dest: "/home/{{ podman_user.name }}/.config/containers/systemd/qbittorrent.container"
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now qbittorrent.service
  ansible.builtin.systemd: name=qbittorrent.service enabled=true state=started scope=user
  become: true
  become_user: "{{ podman_user.name }}"
