---
- name: radarr container config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.radarr_config_dir }}"
    state: directory
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true

- name: radarr.service
  ansible.builtin.template:
    src: radarr.service.j2
    dest: "/home/{{ podman_user.name }}/.config/systemd/user/radarr.service"
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now radarr.service
  ansible.builtin.systemd: name=radarr enabled=true state=started scope=user
  become: true
  become_user: "{{ podman_user.name }}"
