---
- name: container config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.container_configs_dir }}/swag"
    state: directory
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true
  become_user: "{{ podman_user.name }}"

- name: swag.service
  ansible.builtin.template:
    src: swag.service.j2
    dest: "/home/{{ podman_user.name }}/.config/systemd/user/swag.service"
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable swag.service
  ansible.builtin.systemd: name=swag enabled=true scope=user

- name: Set firewall rules for incoming connection
  ansible.posix.firewalld:
    rich_rule: "{{ item }}"
    zone: "{{ firewalld_default_zone }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ podman_user.swag_firewall_rules }}"
  become: true
