---
- name: container config direcoty
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/container_configs/swag"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: '0700'

- name: swag.service
  ansible.builtin.template:
    src: swag.service.j2
    dest: /etc/systemd/system/swag.service
    owner: root
    group: root
    mode: '0644'

- name: systemctl --user daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

- name: systemctl --user enable swag.service
  ansible.builtin.systemd:
    name: swag
    enabled: yes
    scope: user

- name: Allow ufw incoming rules for web interface
  community.general.ufw:
    route: yes
    rule: allow
    interface_in: "{{ static_nic }}"
    from_ip: "{{ item }}"
    to_ip: any
    proto: tcp
    port: 443
    comment: "Allow access web interface from {{ item }}"
  when: ansible_facts['os_family'] == "Archlinux" or ansible_facts['os_family'] == "Debian"
  become: yes
  loop: "{{ allow_web_from }}"

