---
- name: container config direcoty
  ansible.builtin.file:
    path: "{{ container_configs_dir.path }}/swag"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: swag.service
  ansible.builtin.template:
    src: swag.service.j2
    dest: /etc/systemd/system/swag.service
    owner: root
    group: root
    mode: '0644'

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: systemctl enable swag.service
  ansible.builtin.systemd:
    name: swag
    enabled: yes

- name: Allow ufw incoming rules for web interface
  community.general.ufw:
    route: yes
    rule: allow
    interface_in: "{{ static_nic }}"
    from_ip: "{{ item }}"
    to_ip: any
    proto: tcp
    port: 443
    comment: "Allow access web interface from {{ item }}"
  loop: "{{ allow_web_from }}"

