---
- name: syncthing container config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.syncthing_config_dir }}"
    state: directory
    owner: "{{ podman_user.name}}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true

- name: syncthing.service
  ansible.builtin.template:
    src: syncthing.service.j2
    dest: "/home/{{ podman_user.name }}/.config/systemd/user/syncthing.service"
    owner: "{{ podman_user.name}}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now syncthing.service
  ansible.builtin.systemd: name=syncthing enabled=true state=started scope=user
  become: true
  become_user: "{{ podman_user.name }}"


# 22000/tcp    Syncthing Listening port
- name: add syncthing firewalld service file syncthing.xml
  ansible.builtin.copy:
    content: |
      <?xml version="1.0" encoding="utf-8"?>
      <service>
        <short>Syncthing</short>
        <description>Syncthing</description>
        <port protocol="tcp" port="22000"/>
      </service>
    dest: /etc/firewalld/services/syncthing.xml
    owner: root
    group: root
    mode: '0644'
  become: true
  register: syncthing_firewalld_file

- name: Reload firewalld when syncthing.xml changed
  ansible.builtin.command: firewall-cmd --reload
  become: true
  when: syncthing_firewalld_file.changed

- name: Set firewall rules for Syncthing Listening port (TCP)
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" source address="{{ item }}" service name="syncthing" accept
    zone: "{{ firewalld_default_zone }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ podman_user.syncthing_accept_source_ipv4 }}"
  become: true
  when: podman_user.syncthing_accept_source_ipv4 is defined
