---
- name: container config direcoty
  ansible.builtin.file:
    path: "{{ container_configs_dir.path }}/syncthing"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: syncthing.service
  ansible.builtin.template:
    src: syncthing.service.j2
    dest: /etc/systemd/system/syncthing.service
    owner: root
    group: root
    mode: '0644'

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: systemctl enable syncthing.service
  ansible.builtin.systemd:
    name: syncthing
    enabled: yes

#- name: Set UFW incoming roles for Syncthing WebUI
#  community.general.ufw:
#    route: yes
#    rule: allow
#    interface_in: "{{ static_nic }}"
#    from_ip: "{{ item }}"
#    to_ip: any
#    proto: tcp
#    port: 8384
#    comment: "Allow Syncthing application WebUI from {{ item }}"
#  loop: "{{ syncthing_allow_web_from }}"

- name: Set UFW incoming rules for Syncthing Listening port (TCP)
  community.general.ufw:
    route: yes
    rule: allow
    interface_in: "{{ static_nic }}"
    from_ip: "{{ item }}"
    to_ip: any
    proto: tcp
    port: 22000
    comment: "Allow Syncthing listening port (TCP) from {{ item }}"
  loop: "{{ syncthing_allow_from }}"

- name: Set UFW incoming rules for Syncthing Listening port (UDP)
  community.general.ufw:
    route: yes
    rule: allow
    interface_in: "{{ static_nic }}"
    from_ip: "{{ item }}"
    to_ip: any
    proto: udp
    port: 22000
    comment: "Allow Syncthing listening port (TCP) from {{ item }}"
  loop: "{{ syncthing_allow_from }}"

  #- name: Set UFW incoming rules for Syncthing Protocol discovery
  #  community.general.ufw:
  #    route: yes
  #    rule: allow
  #    interface_in: "{{ static_nic }}"
  #    from_ip: "{{ item }}"
  #    to_ip: any
  #    proto: udp
  #    port: 21027
  #    comment: "Allow Syncthing Protocol discovery from {{ item }}"
  #  loop: "{{ syncthing_allow_from }}"

