---
- block:
  - name: syncthing container config direcoty
    ansible.builtin.file:
      path: "{{ container_configs_dir }}/syncthing"
      state: directory
      owner: "{{ podman_user}}"
      group: "{{ podman_user }}"
      mode: '0700'

  - name: syncthing.service
    ansible.builtin.template:
      src: syncthing.service.j2
      dest: "/home/{{ podman_user }}/.config/systemd/user/syncthing.service"
      owner: "{{ podman_user}}"
      group: "{{ podman_user }}"
      mode: '0600'

  - name: systemctl --user enable syncthing.service
    ansible.builtin.systemd:
      name: syncthing
      enabled: yes
      scope: user

  become: yes
  become_user: "{{ podman_user }}"


- name: Set firewall rules for Syncthing Listening port (TCP)
  ansible.posix.firewalld:
    rich_rule: "{{ item }}"
    zone: "{{ firewalld_default_zone }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ syncthing_firewall }}"
  when: syncthing_firewall is defined
  become: yes
