---
- name: tailscale container config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.tailscale_config_dir }}"
    state: directory
    owner: "{{ podman_user.name}}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true

- name: tailscale.service
  ansible.builtin.template:
    src: tailscale.service.j2
    dest: "/home/{{ podman_user.name }}/.config/systemd/user/tailscale.service"
    owner: "{{ podman_user.name}}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable tailscale.service
  ansible.builtin.systemd: name=tailscale.service enabled=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

