---
- name: thelounge container config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.container_configs_dir }}/thelounge"
    state: directory
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true
  become_user: "{{ podman_user.name }}"

- name: thelounge.service
  ansible.builtin.template:
    src: thelounge.service.j2
    dest: "/home/{{ podman_user.name }}/.config/systemd/user/thelounge.service"
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now thelounge.service
  ansible.builtin.systemd: name=thelounge.service enabled=true state=started scope=user
  become: true
  become_user: "{{ podman_user.name }}"
