---
- name: thelounge container config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.thelounge_config_dir }}"
    state: directory
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true

- name: thelounge.container
  ansible.builtin.template:
    src: thelounge.container.j2
    dest: "/home/{{ podman_user.name }}/.config/containers/systemd/thelounge.container"
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now thelounge.service
  ansible.builtin.systemd: name=thelounge.service enabled=true state=started scope=user
  become: true
  become_user: "{{ podman_user.name }}"
  ignore_errors: "{{ ansible_check_mode }}"
