---
- name: pacman -S archlinux-contrib
  community.general.pacman: name=archlinux-contrib state=present
  become: true

- name: auto-update.service
  ansible.builtin.copy:
    src: auto-update.service
    dest: /etc/systemd/system/auto-update.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: auto-update.timer
  ansible.builtin.template:
    src: auto-update.timer.j2
    dest: /etc/systemd/system/auto-update.timer
    owner: root
    group: root
    mode: '0644'
  become: true

- name: auto-update.sh
  ansible.builtin.template:
    src: auto-update.sh.j2
    dest: /usr/local/bin/auto-update.sh
    owner: root
    group: root
    mode: '0700'
  become: true

- name: systemctl daemon-reload
  ansible.builtin.systemd: daemon_reload=true
  become: true

- name: systemctl enable auto-update.timer
  ansible.builtin.systemd: name=auto-update.timer enabled=true state=started
  become: true
