---
- name: apt install unattended-upgrades
  ansible.builtin.apt: name=unattended-upgrades state=present
  become: true

- name: Check /etc/apt/apt.conf.d/20auto-upgrades stats
  ansible.builtin.stat:
    path: /etc/apt/apt.conf.d/20auto-upgrades
  register: auto_upgrades
  become: true

- name: Create /etc/apt/apt.conf.d/20auto-upgrades if not exists
  ansible.builtin.shell: |
    echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
    dpkg-reconfigure -f noninteractive unattended-upgrades
  become: true
  when: not auto_upgrades.stat.exists

- name: 20auto-upgrades config
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - { line: 'APT::Periodic::Update-Package-Lists "1";', regexp: '^APT::Periodic::Update-Package-Lists' }
    - { line: 'APT::Periodic::Unattended-Upgrade "1";', regexp: '^APT::Periodic::Unattended-Upgrade' }
  become: true

- name: /etc/apt/apt.conf.d/50unattended-upgrades set Automatic-Reboot-Time
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
  loop:
    - { regexp: '^Unattended-Upgrade::Automatic-Reboot ', insertafter: '^//Unattended-Upgrade::Automatic-Reboot ', line: 'Unattended-Upgrade::Automatic-Reboot "true";' }
    - { regexp: '^Unattended-Upgrade::Automatic-Reboot-WithUsers ', insertafter: '^//Unattended-Upgrade::Automatic-Reboot-WithUsers ', line: 'Unattended-Upgrade::Automatic-Reboot-WithUsers "true";' }
    - { regexp: '^Unattended-Upgrade::Remove-Unused-Dependencies ', insertafter: '^//Unattended-Upgrade::Remove-Unused-Dependencies ', line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' }
  become: true

- name: Create override directory for apt-daily-upgrade.timer
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
  when: auto_update_time is defined

- name: Set upgrade time
  ansible.builtin.copy:
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    content: |
      [Timer]
      OnCalendar=
      OnCalendar={{ auto_update_time }}
      RandomizedDelaySec=0
  become: true
  when: auto_update_time is defined

