---
- name: apt install unattended-upgrades apt-listchanges
  ansible.builtin.apt:
    pkg:
      - unattended-upgrades
      - apt-listchanges
    state: present
  become: true

- name: Check /etc/apt/apt.conf.d/20auto-upgrades stats
  ansible.builtin.stat:
    path: /etc/apt/apt.conf.d/20auto-upgrades
  register: auto_upgrades
  become: true

- name: Create /etc/apt/apt.conf.d/20auto-upgrades if not exists
  ansible.builtin.shell: |
    echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
    dpkg-reconfigure -f noninteractive unattended-upgrades
  become: true
  when: not auto_upgrades.stat.exists

- name: 20auto-upgrades config
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - { line: 'APT::Periodic::Update-Package-Lists "1";', regexp: '^APT::Periodic::Update-Package-Lists' }
    - { line: 'APT::Periodic::Unattended-Upgrade "1";', regexp: '^APT::Periodic::Unattended-Upgrade' }
  become: true

- name: /etc/apt/apt.conf.d/50unattended-upgrades set Automatic-Reboot-Time
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
  loop:
    - { regexp: '^Unattended-Upgrade::Automatic-Reboot ', insertafter: '^//Unattended-Upgrade::Automatic-Reboot ', line: 'Unattended-Upgrade::Automatic-Reboot "true";' }
    - { regexp: '^Unattended-Upgrade::Remove-Unused-Dependencies ', insertafter: '^//Unattended-Upgrade::Remove-Unused-Dependencies ', line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";' }
  become: true

