---
- name: dnf install dnf-automatic
  ansible.builtin.dnf: name=dnf-automatic state=present
  become: true

- name: Edit /etc/dnf/automatic.conf
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: true
  loop:
    - { regexp: '^apply_updates =', line: "apply_updates = yes" }
    - { regexp: '^reboot =', line: "reboot = when-needed" }

- name: Create /etc/systemd/system/dnf-automatic.timer.d/ directory
  ansible.builtin.file:
    path: /etc/systemd/system/dnf-automatic.timer.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Override default dnf-automatic.timer
  ansible.builtin.template:
    src: dnf-automatic-timer-override.conf.j2
    dest: /etc/systemd/system/dnf-automatic.timer.d/override.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  when: auto_update_time is defined

- name: systemctl enable dnf-automatic.timer
  ansible.builtin.systemd: name=dnf-automatic.timer enabled=true state=started
  become: true

- name: systemctl daemon-reload
  ansible.builtin.systemd: daemon_reload=true
  become: true
