---
- name: sonarr container config direcoty
  ansible.builtin.file:
    path: "{{ podman_user.sonarr_config_dir }}"
    state: directory
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0700'
  become: true

- name: sonarr.service
  ansible.builtin.template:
    src: sonarr.service.j2
    dest: "/home/{{ podman_user.name }}/.config/systemd/user/sonarr.service"
    owner: "{{ podman_user.name }}"
    group: "{{ podman_user.name }}"
    mode: '0600'
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user daemon-reload
  ansible.builtin.systemd: daemon_reload=true scope=user
  become: true
  become_user: "{{ podman_user.name }}"

- name: systemctl --user enable --now sonarr.service
  ansible.builtin.systemd: name=sonarr enabled=true state=started scope=user
  become: true
  become_user: "{{ podman_user.name }}"
