---
- block:
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: apt

  - include_tasks: install_docker.yml
    when: "'docker-ce' not in ansible_facts.packages"

  - name: docker-compose.yml
    ansible.builtin.template:
      src: docker-compose.yml.j2
      dest: "/opt/docker-compose.yml"
      owner: "root"
      group: "root"
      mode: '0600'

  when: ansible_facts['os_family'] == "Debian"
  become: yes

