---
- block:
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: apt

  - include_tasks: debian_install_docker.yml
    when: "'docker-ce' not in ansible_facts.packages"

  when: ansible_facts['distribution'] == "Debian"
  become: yes

- block:
  - name: pacman -S ufw
    community.general.pacman:
      name:
        - docker
        - docker-compose
      state: present

  - name: systemctl enable --now docker.service
    ansible.builtin.systemd: name=docker.service enabled=yes state=started 

  when: ansible_facts['os_family'] == "Archlinux"
  become: yes


- block:
  - name: Copy docker-compose.yml
    ansible.builtin.copy:
      src: "{{ docker_compose_file }}"
      dest: /opt/docker-compose.yml
      owner: root
      group: root
      mode: '0600'

  - name: "Create {{ item }}"
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: '0644'
    loop:
      - docker-compose.service
      - docker-prune.service
      - docker-prune.timer

  - name: systemctl daemon-reload
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: "systemctl enable {{ item }}"
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: yes
    loop:
      - docker-compose.service
      - docker-prune.timer

  become: yes
