---
- block:
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: apt

  - include_tasks: debian_install_docker.yml
    when: "'docker-ce' not in ansible_facts.packages"

  when: ansible_facts['os_family'] == "Debian"
  become: yes


- block:
  - name: pacman -S ufw
    community.general.pacman:
      name:
        - docker
        - docker-compose
      state: present

  - name: systemctl enable --now docker.service
    ansible.builtin.systemd: name=docker.service enabled=yes state=started 

  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
