---
# Whether the home directory is mounted using systemd-homed
homed: true

libvirt_headless: false
libvirt_bridge: true
libvirt_NAT: true

gpu_drivers:
  - mesa

shell_pkgs:
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - grml-zsh-config

default_shell: /usr/bin/zsh

wm_pkgs:
  - sway
  - swaylock
  - swayidle
  - dmenu
  - waybar
  - xdg-utils
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
  - xdg-desktop-portal-gtk 
  - xorg-xwayland
  - python-i3ipc
  - wl-clipboard

dotfiles_repo:
  https: 'https://github.com/username/dotfiles.git'
  ssh: 'git@github.com:username/dotfiles.git'

audio_pkgs:
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - pipewire-jack
  - pavucontrol

fonts_pkgs:
  - ttf-dejavu
  - noto-fonts-cjk
  - ttf-font-awesome
  - noto-fonts-emoji

other_pkgs:
  - kitty
  - htop
  - pass
  - neofetch

  - rsync
  - usbutils
  - brightnessctl   # screen brightness

  - nm-connection-editor
  - system-config-printer
  - gscan2pdf
  - yt-dlp
  - mkvtoolnix-cli

flatpak_pkgs:
  - com.github.tchx84.Flatseal
  - org.kde.dolphin
  - org.kde.okular
  - io.mpv.Mpv
  - org.kde.gwenview
  - io.gitlab.librewolf-community
  - org.mozilla.firefox

  - org.keepassxc.KeePassXC
  - org.qbittorent.qBittorrent
  - org.kde.konversation
  - im.riot.Riot
  - com.github.xournalpp.xournalpp
  - org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
  - org.libreoffice.LibreOffice
  - com.github.johnfactotum.Foliate
  #- com.github.iwalton3.jellyfin-media-player

  - com.valvesoftware.Steam
  - com.usebottles.bottles

pip_pkgs:
  - numpy
  - ipython
  - scipy
  - matplotlib


