---
###############################################################################
# roles/common
# Use Reflector automatically update mirror list.
# https://wiki.archlinux.org/title/Reflector
#
# reflector_country: France,Germany
# will only use mirrors from France and Germany
# To get all country names and codes, run
# reflector --list-countries 
reflector_country: us

###############################################################################
# roles/gui

# Whether the home directory is mounted using systemd-homed
homed: false

gpu_drivers:
  - mesa

shell_pkgs:
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - grml-zsh-config

default_shell: /usr/bin/zsh

# Packages for your Desktop environment or window manager.
wm_pkgs:
  # Example: sway
  - sway
  - swaylock
  - swayidle
  - waybar
  - xdg-utils
  - xdg-desktop-portal
  - xorg-xwayland
  - wl-clipboard
  - xdg-desktop-portal-wlr
  # Firefox file chooser needs xdg-desktop-portal-gtk
  - xdg-desktop-portal-gtk
  # python-i3ipc needed for https://github.com/Bai-Chiang/dotfiles/blob/main/.config/sway/inactive-windows-transparency.py
  - python-i3ipc
  # grim and slurp for screenshoot
  - grim
  - slurp
  # notification daemon
  - mako

  # KDE
  - plasma-meta
  - plasma-wayland-session
  - sddm
  - phonon-qt5-vlc

dotfiles_repo:
  # https link to your dotfiles repo. This should be a public repo.
  https: 'https://github.com/username/dotfiles.git'

  # ssh link to your dotfiles repo. The playbook will replace the https link with ssh link after clone all dotfiles.
  # To push updates to GitHub,  you need to create an ssh key then add the key to your GitHub account.
  ssh: 'git@github.com:username/dotfiles.git'

audio_pkgs:
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - pipewire-jack
  - wireplumber

fonts_pkgs:
  - ttf-dejavu
  - noto-fonts-cjk
  - ttf-font-awesome
  - noto-fonts-emoji

other_pkgs:
  - kitty
  - htop
  - pass
  - neofetch

  # screen brightness
  - brightnessctl
  # printer config
  - system-config-printer
  # scanning tool
  - gscan2pdf

  # yt-dlp
  - yt-dlp
  - ffmpeg

flatpak_pkgs:
  - com.github.tchx84.Flatseal
  - io.mpv.Mpv
  - io.gitlab.librewolf-community
  - org.mozilla.firefox

  - org.kde.dolphin
  - org.kde.gwenview
  - org.kde.okular
  - org.kde.kwrite


###############################################################################
# roles/podman

# TZ enviroment variable for LSIO images.
TZ: "US/Eastern"

# Running podman as rootless user
# name and uid specify the username and UID value.
# The user will be created if not exists.
podman_users:
  - name: tux
    uid: 1000

    # enable lingering for the user will automatic start systemd user instance on start-up.
    enable_lingering: false

    # The frequency of running podman system prune, in systemd-timer format.
    podman_system_prune_timer: daily

    container_configs_dir: "/home/tux/container_configs"
    containers:
      - syncthing
    syncthing_data_dirs:
      - { src: /home/tux/data, dest: /data }


