---
###############################################################################
# roles/common
reflector_country: us

###############################################################################
# roles/gui

# Whether the home directory is mounted using systemd-homed
homed: false

gpu_drivers:
  - mesa

shell_pkgs:
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - grml-zsh-config

default_shell: /usr/bin/zsh

wm_pkgs:
  # sway
  - sway
  - swaylock
  - swayidle
  - waybar
  - xdg-utils
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
  - xdg-desktop-portal-gtk 
  - xorg-xwayland
  - python-i3ipc
  - wl-clipboard
  - grim
  - slurp
  - mako

  # KDE
  - plasma-meta
  - plasma-wayland-session
  - dolphin
  - ark
  - ffmpegthumbs
  - kdegraphics-thumbnailers
  - konsole
  - phonon-qt5-vlc

dotfiles_repo:
  # https link to your dotfiles repo. This should be a public repo.
  https: 'https://github.com/username/dotfiles.git'

  # ssh link to your dotfiles repo. The playbook will replace the https link with ssh link after clone all dotfiles.
  # To push updates to GitHub,  you need to create an ssh key then add the key to your GitHub account.
  ssh: 'git@github.com:username/dotfiles.git'

audio_pkgs:
  - pipewire
  - pipewire-alsa
  - pipewire-pulse
  - pipewire-jack
  - wireplumber

  - pavucontrol

fonts_pkgs:
  - ttf-dejavu
  - noto-fonts-cjk
  - ttf-font-awesome
  - noto-fonts-emoji

other_pkgs:
  - kitty
  - htop
  - pass
  - neofetch

  - brightnessctl   # screen brightness
  - system-config-printer
  - gscan2pdf

flatpak_pkgs:
  - com.github.tchx84.Flatseal
  - io.mpv.Mpv
  - io.gitlab.librewolf-community
  - org.mozilla.firefox


###############################################################################
# roles/podman
TZ: "US/Eastern"

podman_users:
  - name: tux
    uid: 1000
    enable_lingering: false
    podman_system_prune_timer: daily
    container_configs_dir: "/home/tux/container_configs"
    containers:
      - syncthing
    syncthing_data_dirs:
      - { src: /home/tux/data, dest: /data }



