---
- name: "import_tasks: raid.yml"
  import_tasks: raid.yml
  when: crypttab_entries is defined or fstab_entries is defined

- name: "import_tasks: btrfs_scrub.yml"
  import_tasks: btrfs_scrub.yml
  when: btrfs_scrub_path is defined

- name: "import_tasks: smartd.yml"
  import_tasks: smartd.yml
  when: smartd_time is defined

- name: "import_tasks: nfs.yml"
  import_tasks: nfs.yml
  when: nfs_mount_point is defined

- name: "include_tasks: samba.yml"
  include_tasks: samba.yml
  when: smb_share is defined

