---
- block:

  - import_tasks: raid.yml
  - import_tasks: btrfs_scrub.yml
  - import_tasks: smartd.yml
  - import_tasks: nfs.yml
    when: nfs_mount_point is defined
  - include_tasks: samba.yml
    when: smb_passwd is defined

  become: yes
