---
- name: pacman -S nfs-utils
  community.general.pacman:
    name: nfs-utils
    state: present

- name: Create NFS directories
  ansible.builtin.file:
    path: "{{ item.bind }}"
    state: directory
  loop: "{{ nfs_mount_point }}"

- name: Add bind mount to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "^{{ item.target }}\\s+{{item.bind }}"
    line: "{{ item.target }}  {{item.bind }}  none  bind  0 0"
    state: present
  loop: "{{ nfs_mount_point }}"

- name: add root mount to /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: "^{{ nfs_root }}\\s+"
    line: "{{ nfs_root }}  {{ nfs_root_ip_opt }}"
    state: present

- name: add other mount points to /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: "^{{ item.bind }}\\s+"
    line: "{{ item.bind }}  {{ item.ip_opt }}"
    state: present
  loop: "{{ nfs_mount_point }}"

#- name: Add custom NFS rule to UFW
#  ansible.builtin.blockinfile:
#    path: /etc/ufw/applications.d/ufw-custom
#    block: | 
#      [NFS-custom]
#      title=NFS server
#      description=NFS server
#      ports=2049/tcp
#    create: yes
#    marker: "; NFS {mark} ANSIBLE MANAGED BLOCK"
#
#- name: Configure firewall for NFS
#  community.general.ufw:
#    rule: allow
#    direction: in
#    name: NFS-custom
#    from: "{{ item }}"
#    comment: "Allow NFS from {{ item }}"
#  loop: "{{ nfs_allow_ip }}"
#
- name: Set firewall rules for NFS
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" source address="{{ item }}" port port="2049" protocol="tcp" accept
    zone: "{{ firewalld_default_zone }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ nfs_allow_from_ipv4 }}"
  when: nfs_allow_from_ipv4 is defined
  become: yes

- name: systemctl enable nfs-server.service
  ansible.builtin.systemd:
    name: nfs-server
    enabled: yes
