---
- name: dnf install cryptsetup
  ansible.builtin.dnf: name=cryptsetup state=present
  become: true
  when: ansible_distribution == "Fedora"

- name: Create /etc/crypttab file
  ansible.builtin.file:
    path: /etc/crypttab
    state: touch
    owner: root
    group: root
    mode: '0644'
    modification_time: preserve
    access_time: preserve
  become: true
  when: ansible_distribution == "Fedora"
  
- name: Edit /etc/crypttab
  ansible.builtin.lineinfile:
    path: /etc/crypttab
    regexp: "^{{ item.device_mapper_name }}"
    line: "{{ item.device_mapper_name}}    UUID={{ item.UUID }}    {{ item.keyfile }}"
    state: present
  loop: "{{ crypttab_entries }}"
  become: true

- name: Create mount points
  ansible.builtin.file:
    path: "{{ item.mount_point }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ fstab_entries }}"
  become: true

- name: Edit /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "^{{ item.device }}\\s+{{ item.mount_point }}\\s+"
    line: "{{ item.device }}    {{ item.mount_point }}    {{ item.fs }}    {{ item.mount_opts }}    0 0 "
    state: present
  loop: "{{ fstab_entries }}"
  become: true

