---
- name: pacman -S samba
  community.general.pacman: name=samba state=present
  become: true

- name: Create /etc/samba/smb.conf
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    validate: testparm -s %s
  become: true

#- name: Add custom Samba rule to UFW
#  ansible.builtin.blockinfile:
#    path: /etc/ufw/applications.d/ufw-custom
#    block: | 
#      [Samba-custom]
#      title=SMB/CIFS server
#      description=SMB/CIFS server
#      ports=445/tcp
#    create: true
#    marker: "; SMB/CIFS {mark} ANSIBLE MANAGED BLOCK"
#
#- name: Configure firewall for CIFS
#  community.general.ufw:
#    rule: allow
#    direction: in
#    name: Samba-custom
#    from: "{{ item }}"
#    comment: "Allow SMB/CIFS from {{ item }}"
#  loop: "{{ CIFS_allow_ip }}"

- name: Add samba user
  shell: (echo {{ smb_passwd }}; echo {{ smb_passwd }}) | smbpasswd -s -a {{ ansible_user_id }}
  register: samba_user
  changed_when: "'Added user' in samba_user.stdout"

- name: systemctl enable smb.service
  ansible.builtin.systemd: name=smb enabled=true
