---
- name: Generate key
  ansible.builtin.shell: |
    wg genkey | (umask 0077 && tee /etc/wireguard/private.key) | wg pubkey > /etc/wireguard/public.key

- name: Get private.key
  ansible.builtin.command: cat /etc/wireguard/private.key
  register: wg_private
  changed_when: False

- name: Get public.key
  ansible.builtin.command: cat /etc/wireguard/public.key
  register: wg_public
  changed_when: False

- name: add wg0 interface
  ansible.builtin.shell: |
    ip link add dev wg0 type wireguard
    ip addr add dev wg0 {{ wg_internal_ip }}
    wg set wg0 listen-port {{ wg_port }} private-key /etc/wireguard/private.key
    ip link set dev wg0 up

- name: Save config file
  ansible.builtin.shell: |
    wg showconf wg0 > /etc/wireguard/wg0.conf
