---

- name: Get stats of wireguard private key
  ansible.builtin.stat:
    path: /etc/wireguard/private.key
  register: wg_private_key_file

- name: Get stats of wireguard public key
  ansible.builtin.stat:
    path: /etc/wireguard/public.key
  register: wg_public_key_file

- name: Generate key
  ansible.builtin.shell: |
    wg genkey | (umask 0077 && tee /etc/wireguard/private.key) | wg pubkey > /etc/wireguard/public.key
  when: not ( wg_private_key_file.stat.exists and wg_public_key_file.stat.exists )

- name: Get private.key
  ansible.builtin.command: cat /etc/wireguard/private.key
  register: wg_private_key
  changed_when: False

- name: Get public.key
  ansible.builtin.command: cat /etc/wireguard/public.key
  register: wg_public_key
  changed_when: False

- name: wg0.conf
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'

- name: Create wg_interface_name variable
  ansible.builtin.set_fact:
    wg_interface_name: wg0

