---
- name: ufw default deny outgoing rule
  community.general.ufw: default=deny direction=outgoing

- name: ufw allow outgoing connection to wireguard server
  community.general.ufw:
    rule: allow
    direction: out
    dest: "{{ wg_endpoint_address }}"
    port: "{{ wg_endpoint_port }}"
    comment: allow wireguard connection
    
- name: "ufw only allow outgoing connection through {{ wg_interface_name }}"
  community.general.ufw:
    rule: allow
    direction: out
    interface: "{{ wg_interface_name }}"
    comment: "allow traffic through {{ wg_interface_name }}"
